server:
  port: ${appPort:80}
#  additionalPorts: 28647

## Spring MVC actuator endpoints available via /admin/info, /admin/health, ...
#server.servlet-path: /
#management:
#  context-path: /admin
#  port: 8881
#
#javaMelodyPort: 8883
#
## http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints
#endpoints:
#  enabled: false
#  info:
#    enabled: true
#  health:
#    enabled: true
#  metrics:
#    enabled: true

info:
  app:
    name: APIProject
  build:
    version: 0.0.1-SNAPSHOT
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@//14.225.7.153:41521/EE.oracle.docker
#    username: yougame
#    password: ygm420ald
#    driver-class-name: oracle.jdbc.OracleDriver